# Setup
title:               Blog Needs a Name
description:         ''
url:                 'https://ahgamut.github.io'
baseurl:             ''
paginate:            5
permalink:           pretty
markdown:            kramdown

author:
  name:              Gautham Venkatasubramanian
  url:               https://github.com/ahgamut

plugins:
  - jekyll-paginate
  - jekyll-minifier

kramdown:
  math_engine: katex
  math_engine_opts: {}

exclude:
  - LICENSE.md
  - README.md
