# Setup
title:               Blog Needs a Name
description:         'Gautham writes about his programming?'
url:                 'https://ahgamut.github.io'
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Gautham Venkatasubramanian
  url:               https://github.com/ahgamut

# Gems
plugins:
  - jekyll-paginate
